### ISSUE TITLE
Linuxcounter Updater App fails on Android One

### ISSUE THREAD

**Issue by ulihh** [christinloehner/linuxcounter.new#103]
Hi, I have a HTC U11 Life with android 8.0.0 and the linuxcounter updater app doesn't upload any data. I have made a logcat with the following lines appearing when I press the "Send data..." button:

06-04 18:44:19.968 30731 30731 I MyDebugOutput: sendSysInfo: start postData()...
06-04 18:44:19.969 30731 30731 I MyDebugOutput: sendSysInfo: start Volley Send POST()...
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  url=http://api.linuxcounter.net/v1/machines/2027711
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  machine_id=2027711
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  machine_updatekey=XXXXXXXX
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  appversion=0.0.9
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  hostname=localhost
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  cores=8
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  flags=fp asimd evtstrm aes pmull sha1 sha2 crc32
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  diskspace=43473320
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  diskspaceFree=32130640
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  memory=2796684
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  memoryFree=199380
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  swap=1398340
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  swapFree=468372
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  distversion=8.0.0
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  online=1
06-04 18:44:19.979 30731 19095 I MyDebugOutput: sendSysInfo: PATCH data:  uptime=18:44:14 up 8 days
06-04 18:44:19.980 30731 19095 E Volley  : [6889] NetworkDispatcher.run: Unhandled exception java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
06-04 18:44:19.980 30731 19095 E Volley  : java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
06-04 18:44:19.980 30731 19095 E Volley  : 	at com.linuxcounter.lico_update_003.sendSysInfo$3.getParams(sendSysInfo.java:72)
06-04 18:44:19.980 30731 19095 E Volley  : 	at com.android.volley.Request.getBody(Request.java:475)
06-04 18:44:19.980 30731 19095 E Volley  : 	at com.android.volley.toolbox.HurlStack.addBodyIfExists(HurlStack.java:236)
06-04 18:44:19.980 30731 19095 E Volley  : 	at com.android.volley.toolbox.HurlStack.setConnectionParametersForRequest(HurlStack.java:214)
06-04 18:44:19.980 30731 19095 E Volley  : 	at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:106)
06-04 18:44:19.980 30731 19095 E Volley  : 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
06-04 18:44:19.980 30731 19095 E Volley  : 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)

The machine_updatekey in the original msg is different of course.
Maybe someone can fix this issue?
Thanks,
Ulrich

**Comment by philb61** [comment]
Not sure if this is the same issue (haven't installed the toolbox to read logs), but I can confirm that the app (version 0.0.9) seems not to update anything at all on my OnePlus 6.
